/* Presentation copy only. Scientific checks run in the shared Python audit core. */
"use strict";
const COPY = {
  zh: {
    advancedDrop: "拖放文件，或一次选择多份文件",
    advancedDropHint:
      "按文件名识别 samples、design、observations、assays；也可逐项选择。",
    namedFiles:
      "多文件导入请使用 samples.csv/tsv、design.yaml/yml、observations.csv/tsv、assays.csv/tsv，且每类仅一份。",
    designType: "请选择 YAML 设计文件。",
    skip: "跳到主要内容",
    local: "本机处理",
    quit: "退出",
    hero: "先确认设计，<br>再推进分析。",
    lead: "从一张细胞表开始，或声明完整的研究设计。<br>明确生物学重复、批次分配，以及你想做的比较。",
    oneEngine: "两种入口，同一检查引擎",
    privacy: "无需账户 · 不上传云端",
    footer: "可追溯证据 · 离线报告 · 合成示例",
    working: "正在本机处理",
    wait: "请稍候，完成后会显示结果。",
    quick: "快速检查",
    quickIntro: "一张细胞表，逐步确认字段与比较",
    advanced: "高级设计",
    advancedIntro: "样本表与设计声明，支持协变量和配对模型",
    entryMode: "选择工作方式",
    alpha: "早期版本",
    choose: "选择文件",
    drop: "将细胞元数据拖到这里",
    dropCopy: "CSV / TSV · 每行一个细胞 · UTF-8",
    quickLimit: "最大 10 MiB / 100,000 行 / 256 列",
    quickTitle: "从一张元数据表开始",
    quickCopy: "不需要表达矩阵。先预览，再确认每一列代表什么。",
    localCopy: "文件仅由本机服务处理；运行完成后保存报告包。原始表不会被修改。",
    noH5ad:
      "当前统一工作台接收 CSV/TSV。使用 h5ad 时，请先导出所需的 adata.obs 列。",
    changed: "重新选文件",
    rows: "行细胞记录",
    columns: "列",
    mappingTitle: "确认字段含义",
    mappingHelp: "必填角色须对应不同列。真实独立性由研究者确认。",
    selectColumn: "选择一列…",
    omit: "不纳入本次检查",
    optional: "可选",
    sample: "样本 / 文库",
    unit: "供体 / 生物学单位",
    target: "实验条件",
    batch: "技术批次",
    cell_type: "细胞类型",
    timepoint: "时间点",
    cell_id: "细胞 ID",
    sampleHelp: "同一样本的设计信息应保持一致",
    unitHelp: "同一动物或受试者共用一个 ID",
    targetHelp: "你希望比较的分组；也可以是时间分组",
    batchHelp: "建库或测序等技术分配变量",
    cell_typeHelp: "已有的注释，不在此判断准确性",
    timepointHelp: "主动选择后作为分类调整项，不能与条件重复",
    cell_idHelp: "选择后核对原始 ID 的全局唯一性",
    mappingMissing: "请补齐五个必填角色。",
    mappingDuplicate: "不同角色不能重复选择同一列。",
    confirmStudy: "明确这次要比较什么",
    comparisonHelp:
      "方向、采样方式和模型都需要你确认。工具不自动推断配对关系。",
    numerator: "目标组",
    denominator: "参考组",
    selectLevel: "选择条件…",
    direction: "本次比较",
    mode: "采样方式",
    selectMode: "请选择采样方式…",
    independent: "独立：每个供体一个样本",
    paired: "配对：每个供体在两个条件下各一个样本",
    studySummary: "已识别",
    samples: "样本",
    units: "生物学单位",
    observations: "细胞 / 点位",
    repeatHint:
      "存在重复取样。若是配对设计请明确选择；其他复杂重复结构会标记为未评估。",
    modelHint:
      "快速模式使用分类加性模型：条件 + 批次 + 可选时间点；配对模式另加供体阻断项。连续协变量使用高级模式。",
    thresholds: "供体覆盖复核阈值",
    thresholdHint:
      "按供体 × 条件 × 细胞类型合并计数。这些阈值不是样本量或功效结论。",
    min_units: "最少供体数",
    min_cells: "每供体最少细胞数",
    dominance: "单供体占比阈值",
    preview: "元数据预览",
    previewHelp: "显示前 5 行、前 8 列。审计使用全部已选列。",
    runQuick: "生成设计审计",
    ready: "字段、比较方向和采样方式已确认。",
    notReady: "请确认字段、比较方向、采样方式及有效阈值。",
    handoff: "转为高级输入",
    handoffNote:
      "已转换为标准样本、观测表和设计文件。可下载、修改后重新选入；没有运行新的审计。生成的行编号仅用于关联记录，不证明原始细胞 ID 唯一。",
    advancedTitle: "使用明确的研究设计",
    advancedCopy:
      "上传样本表和 YAML 设计声明；支持指定比较、数值协变量及严格配对设计。",
    samplesFile: "样本表",
    designFile: "设计文件",
    observationsFile: "细胞 / 空间点位表",
    assaysFile: "实验测定关联表",
    required: "必填",
    remove: "移除文件",
    notChosen: "尚未选择",
    optionalFiles: "添加可选元数据",
    advancedLimit: "文件合计最大 32 MiB；设计文件最大 1 MB。",
    advancedCoverage:
      "细胞覆盖阈值在 design.yaml 的 cell_coverage 中声明，需提供含 cell_type 的观测表。",
    runAdvanced: "运行高级设计检查",
    chooseBoth: "请添加样本表与设计声明。",
    allFilesReady: "样本表与设计声明已就绪。",
    saveInput: "下载已转换输入",
    demoTitle: "先用示例熟悉工具",
    demoCopy: "原创合成元数据，不含真实研究记录。",
    balanced: "均衡分配",
    confounded: "条件与批次混杂",
    pairedDemo: "配对供体",
    confoundedTime: "时间与批次混杂",
    partial: "批次部分重叠",
    redundant: "调整变量冗余",
    spatial: "空间重复采样",
    mixed: "跨批次实验测定",
    demo: "打开示例报告",
    template: "下载示例输入",
    learnTitle: "细胞多，也要看供体数。",
    learnCopy:
      "来自同一动物的多份文库不会增加独立重复。判断一个具体比较时，还需要声明采样方式与调整变量。",
    boundary:
      "没有风险标记、或显示“可估计”，都不代表统计功效、因果关系或生物学结论已经成立。",
    resultTitle: "本次设计审计",
    synthetic: "合成示例",
    downloadHtml: "下载中文报告",
    downloadZip: "下载完整报告包",
    downloadJson: "下载 JSON",
    saved: "报告已保存到本机",
    scope:
      "报告使用局部 ID 别名；标签和设计取值仍可能包含可识别信息，分享前请检查。",
    overview: "概览与建议",
    report: "完整报告",
    provenance: "输入与模型",
    reviewFlags: "复核提示",
    critical: "优先复核",
    warning: "需关注",
    info: "范围说明",
    all: "全部",
    findings: "逐条复核",
    nextStep: "建议下一步",
    evidence: "查看具体证据",
    noFindings: "当前筛选下没有提示。",
    noFlags: "没有触发当前配置的规则。请继续结合研究背景和统计模型复核。",
    ESTIMABLE: "可估计",
    NON_ESTIMABLE: "不可估计",
    NOT_ASSESSED: "未评估",
    estimableHint: "仅表示声明模型下的代数可估计性。",
    notAssessedHint: "采样结构超出当前模型支持范围；描述性检查仍已执行。",
    coverageTitle: "细胞类型中的供体支持",
    coverageEmpty: "本次未启用细胞类型供体阈值检查。",
    cells: "细胞数",
    eligible: "样本表中的供体",
    supported: "达到阈值的供体",
    share: "最高供体占比",
    rawConfig: "完整设计声明（标准 JSON）",
    adapter: "导入映射与原始文件指纹",
    standardMode: "标准样本表与设计声明",
    onlyMapped: "仅选中的列进入转换。时间点默认不纳入模型。",
    stopped: "BatchLens 已停止。可以关闭此页面；已保存报告仍在本机。",
    networkError:
      "无法连接本机服务，请重新打开 BatchLens。已保存报告仍在输出目录。",
    failed: "无法完成这一步",
    wrongType: "请选择 UTF-8 CSV 或 TSV 文件。",
    emptyFile: "文件为空，请选择包含表头与记录的文件。",
    tooLarge: "文件超过当前入口的大小限制。",
    oneFile: "请一次选择一份细胞元数据表。",
    badUtf8: "文件不是有效的 UTF-8 编码。请重新导出为 UTF-8 CSV/TSV。",
    advancedRequired: "请选择样本表与设计文件。",
    copyLanguage: "English report also included in the bundle.",
    more: "展开",
    less: "收起",
  },
  en: {
    advancedDrop: "Drop files or choose several at once",
    advancedDropHint:
      "Recognizes samples, design, observations and assays by filename. Or choose each below.",
    namedFiles:
      "Use samples.csv/tsv, design.yaml/yml, observations.csv/tsv and assays.csv/tsv; one file per role.",
    designType: "Choose a YAML design file.",
    skip: "Skip to main content",
    local: "Running locally",
    quit: "Quit",
    hero: "Understand the design.<br>Then move forward.",
    lead: "Start with a cell table or an explicit study design.<br>Review biological units, batch allocation and your intended comparison.",
    oneEngine: "Two entry points. One audit engine.",
    privacy: "No account · No cloud upload",
    footer: "Traceable evidence · Offline reports · Synthetic demos",
    working: "Processing on your computer",
    wait: "Keep this window open while the audit completes.",
    quick: "Quick check",
    quickIntro: "One cell table, guided roles and comparison",
    advanced: "Advanced design",
    advancedIntro:
      "Samples and declared model, including covariates and pairing",
    entryMode: "Choose an input mode",
    alpha: "Exploratory alpha",
    choose: "Choose file",
    drop: "Drop cell metadata here",
    dropCopy: "CSV / TSV · One row per cell · UTF-8",
    quickLimit: "Up to 10 MiB / 100,000 rows / 256 columns",
    quickTitle: "Start with one metadata table",
    quickCopy:
      "No expression matrix needed. Preview the data, then confirm each column's role.",
    localCopy:
      "Files are processed locally. Completed report bundles are saved on this computer; original tables are not modified.",
    noH5ad:
      "The unified workbench accepts CSV/TSV. For h5ad, first export the relevant adata.obs columns.",
    changed: "Change file",
    rows: "cell rows",
    columns: "columns",
    mappingTitle: "Confirm the study roles",
    mappingHelp:
      "Required roles need distinct columns. The analyst declares biological independence.",
    selectColumn: "Choose a column…",
    omit: "Do not include",
    optional: "optional",
    sample: "Sample / library",
    unit: "Donor / biological unit",
    target: "Condition",
    batch: "Technical batch",
    cell_type: "Cell type",
    timepoint: "Timepoint",
    cell_id: "Cell ID",
    sampleHelp: "A sample must have consistent study metadata",
    unitHelp: "The same animal or person retains one ID",
    targetHelp: "The grouping to compare; may be a time grouping",
    batchHelp: "Technical allocation, such as sequencing run",
    cell_typeHelp: "Existing annotation; accuracy is not assessed",
    timepointHelp: "Opt in as a categorical adjustment; distinct from target",
    cell_idHelp: "Checks global uniqueness of supplied cell IDs",
    mappingMissing: "Map all five required roles.",
    mappingDuplicate: "Use a distinct column for each role.",
    confirmStudy: "Choose the comparison",
    comparisonHelp:
      "Confirm direction, sampling structure and model. Pairing is never inferred automatically.",
    numerator: "Target group",
    denominator: "Reference group",
    selectLevel: "Choose a condition…",
    direction: "Requested comparison",
    mode: "Sampling structure",
    selectMode: "Choose the sampling structure…",
    independent: "Independent: one sample per biological unit",
    paired: "Paired: one sample per condition per unit, two conditions",
    studySummary: "Identified",
    samples: "Samples",
    units: "Biological units",
    observations: "Cells / spots",
    repeatHint:
      "Repeated sampling is present. Declare pairing if appropriate; unsupported repeated designs are marked not assessed.",
    modelHint:
      "Quick mode uses additive categorical condition + batch + optional timepoint. Paired mode adds a unit block. Use advanced mode for continuous covariates.",
    thresholds: "Donor-coverage review thresholds",
    thresholdHint:
      "Counts pool within unit × condition × cell type. These thresholds are not a sample-size or power calculation.",
    min_units: "Minimum units",
    min_cells: "Minimum cells per unit",
    dominance: "Largest-unit share threshold",
    preview: "Metadata preview",
    previewHelp:
      "First 5 rows and 8 columns. All selected columns and rows are audited.",
    runQuick: "Create design audit",
    ready: "Roles, comparison direction and sampling structure confirmed.",
    notReady:
      "Confirm mapping, comparison, sampling structure and valid thresholds.",
    handoff: "Use as advanced input",
    handoffNote:
      "Converted to standard sample, observation and design files. Download to edit, then select them again. No new audit has run. Generated row IDs link records; they do not establish original cell-ID uniqueness.",
    advancedTitle: "Work from an explicit study design",
    advancedCopy:
      "Provide a sample table and YAML declaration. Supports explicit contrasts, numeric covariates and strict paired designs.",
    samplesFile: "Sample table",
    designFile: "Design declaration",
    observationsFile: "Cells / spots",
    assaysFile: "Assay links",
    required: "required",
    remove: "Remove file",
    notChosen: "Not selected",
    optionalFiles: "Add optional metadata",
    advancedLimit: "Up to 32 MiB combined; design file up to 1 MB.",
    advancedCoverage:
      "Declare cell_coverage in design.yaml to enable donor thresholds; provide observations with cell_type.",
    runAdvanced: "Run advanced audit",
    chooseBoth: "Add samples and design to continue.",
    allFilesReady: "Samples and design are ready.",
    saveInput: "Download converted input",
    demoTitle: "Explore a study first",
    demoCopy: "Original synthetic metadata. No real study records.",
    balanced: "Balanced allocation",
    confounded: "Condition meets batch",
    pairedDemo: "Paired biological units",
    confoundedTime: "Time meets batch",
    partial: "Partial batch overlap",
    redundant: "Redundant adjustment",
    spatial: "Spatial replicates",
    mixed: "Mixed assays",
    demo: "Open example report",
    template: "Download example input",
    learnTitle: "More cells. How many donors?",
    learnCopy:
      "Extra libraries from the same animal do not create independent replicates. A specific contrast also needs a declared sampling structure and adjustment terms.",
    boundary:
      "No flags, or an estimable contrast, does not establish statistical power, causality or a valid biological conclusion.",
    resultTitle: "Your study-design audit",
    synthetic: "SYNTHETIC EXAMPLE",
    downloadHtml: "Download English report",
    downloadZip: "Download report bundle",
    downloadJson: "Download JSON",
    saved: "Saved on this computer",
    scope:
      "Reports use local ID aliases. Labels and design values may still identify people; review all outputs before sharing.",
    overview: "Findings & next steps",
    report: "Full report",
    provenance: "Input & model",
    reviewFlags: "Review flags",
    critical: "Priority review",
    warning: "Review",
    info: "Scope note",
    all: "All",
    findings: "Inspect each finding",
    nextStep: "Suggested next step",
    evidence: "Inspect the evidence",
    noFindings: "No findings match this filter.",
    noFlags:
      "No configured rule fired. Continue reviewing the study context and statistical model.",
    ESTIMABLE: "Estimable",
    NON_ESTIMABLE: "Not estimable",
    NOT_ASSESSED: "Not assessed",
    estimableHint: "Algebraic estimability under the declared model only.",
    notAssessedHint:
      "Sampling is outside the supported model; descriptive checks still ran.",
    coverageTitle: "Donor support within cell types",
    coverageEmpty:
      "Cell-type donor thresholds were not enabled for this audit.",
    cells: "Cells",
    eligible: "Eligible units",
    supported: "Units at threshold",
    share: "Largest unit share",
    rawConfig: "Complete declared design (canonical JSON)",
    adapter: "Column mapping and source fingerprint",
    standardMode: "Standard sample table and design declaration",
    onlyMapped:
      "Only selected columns are adapted. Timepoint is excluded until you opt in.",
    stopped:
      "BatchLens has stopped. You can close this tab. Saved reports remain on this computer.",
    networkError:
      "Cannot reach the local service. Reopen BatchLens. Completed reports remain in the output folder.",
    failed: "This step could not be completed",
    wrongType: "Choose a UTF-8 CSV or TSV file.",
    emptyFile: "The file is empty. Include a header and records.",
    tooLarge: "File size exceeds this input mode's limit.",
    oneFile: "Choose one cell metadata table at a time.",
    badUtf8: "This file is not valid UTF-8. Export UTF-8 CSV/TSV and retry.",
    advancedRequired: "Choose samples and design files.",
    copyLanguage: "中文版报告也包含在报告包内。",
    more: "Expand",
    less: "Collapse",
  },
};
